import {
  FaEye,
  FaEyeSlash,
  FaRegHeart,
  FaUserCircle,
  FaShoppingBag,
  FaUserFriends,
  FaChalkboardTeacher,
  FaUserGraduate,
  FaDiscord,
  FaFacebookF,
  FaYoutube,
  FaInstagram,
  FaTiktok,
  FaTwitter,
} from "react-icons/fa";

import {
  MdMenu,
  MdClose,
  MdNotifications,
  MdDashboard,
  MdCategory,
  MdInventory2,
  MdPeople,
  MdKeyboardArrowDown,
  MdLogout,
} from "react-icons/md";

import {
  IoMenuOutline,
  IoCloseOutline,
  IoSearchOutline,
  IoHomeOutline,
  IoShirtOutline,
  IoPersonOutline,
  IoArrowForward,
} from "react-icons/io5";

export {
  FaEye,
  FaEyeSlash,
  FaRegHeart,
  FaUserCircle,
  FaShoppingBag,
  FaUserFriends,
  FaChalkboardTeacher,
  FaUserGraduate,
  FaDiscord,
  FaFacebookF,
  FaYoutube,
  FaInstagram,
  FaTiktok,
  FaTwitter,
  MdMenu,
  MdClose,
  MdNotifications,
  MdDashboard,
  MdCategory,
  MdInventory2,
  MdPeople,
  MdKeyboardArrowDown,
  MdLogout,
  IoMenuOutline,
  IoCloseOutline,
  IoSearchOutline,
  IoHomeOutline,
  IoShirtOutline,
  IoPersonOutline,
  IoArrowForward,
};
